import type { Trip, TripDestination, ItineraryItem } from '@/types/supabase';

export const mockTrip: Trip = {
  id: 'europe-summer-2026',
  user_id: 'mock-user',
  name: 'Europe Summer 2026',
  status: 'planning',
  start_date: '2026-06-12',
  end_date: '2026-07-03',
  cover_emoji: '🌍',
  total_budget: 9500,
  created_at: '2026-01-01T00:00:00Z',
};

export const mockDestinations: TripDestination[] = [
  {
    id: 'dest-paris',
    trip_id: 'europe-summer-2026',
    city: 'Paris',
    country: 'France',
    airport_code: 'CDG',
    arrival_date: '2026-06-12',
    departure_date: '2026-06-18',
    day_start: 1,
    day_end: 6,
    weather_emoji: '☀️',
    temp_f: 74,
    sort_order: 1,
  },
  {
    id: 'dest-barcelona',
    trip_id: 'europe-summer-2026',
    city: 'Barcelona',
    country: 'Spain',
    airport_code: 'BCN',
    arrival_date: '2026-06-18',
    departure_date: '2026-06-23',
    day_start: 7,
    day_end: 11,
    weather_emoji: '🌤️',
    temp_f: 79,
    sort_order: 2,
  },
  {
    id: 'dest-santorini',
    trip_id: 'europe-summer-2026',
    city: 'Santorini',
    country: 'Greece',
    airport_code: 'JTR',
    arrival_date: '2026-06-23',
    departure_date: '2026-06-29',
    day_start: 12,
    day_end: 17,
    weather_emoji: '☀️',
    temp_f: 82,
    sort_order: 3,
  },
  {
    id: 'dest-rome',
    trip_id: 'europe-summer-2026',
    city: 'Rome',
    country: 'Italy',
    airport_code: 'FCO',
    arrival_date: '2026-06-29',
    departure_date: '2026-07-03',
    day_start: 18,
    day_end: 21,
    weather_emoji: '⛅',
    temp_f: 77,
    sort_order: 4,
  },
];

export const mockItineraryItems: ItineraryItem[] = [
  // Paris Day 1
  {
    id: 'it-1',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-paris',
    date: '2026-06-12',
    time_label: '06:15 AM',
    title: 'Depart TUL — American Airlines AA 1847',
    subtitle: "Tulsa Int'l → Dallas/Fort Worth → Paris CDG · 14h 20m",
    type: 'flight',
    emoji: '✈️',
    cost: 847,
    booked: true,
    sort_order: 1,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-2',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-paris',
    date: '2026-06-12',
    time_label: '09:30 AM (next day)',
    title: 'Check in — Hôtel du Louvre',
    subtitle: '1 Place André Malraux, 75001 Paris · 4★ · $220/night',
    type: 'hotel',
    emoji: '🏨',
    cost: 220,
    booked: true,
    sort_order: 2,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-3',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-paris',
    date: '2026-06-12',
    time_label: '11:00 AM',
    title: 'Brunch — Café de Flore',
    subtitle: '172 Bd Saint-Germain · Iconic Parisian café · ~$22pp',
    type: 'food',
    emoji: '🥐',
    cost: 22,
    booked: false,
    sort_order: 3,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-4',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-paris',
    date: '2026-06-12',
    time_label: '02:00 PM',
    title: 'Eiffel Tower Summit Visit',
    subtitle: 'Tickets pre-booked · Summit access · ~$38pp',
    type: 'activity',
    emoji: '🗼',
    cost: 38,
    booked: true,
    sort_order: 4,
    created_at: '2026-01-01T00:00:00Z',
  },
  // Paris Day 2
  {
    id: 'it-5',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-paris',
    date: '2026-06-13',
    time_label: '09:00 AM',
    title: 'Louvre Museum — Skip-the-line',
    subtitle: 'Full-day visit · Mona Lisa, Venus de Milo · ~$24pp',
    type: 'activity',
    emoji: '🎨',
    cost: 24,
    booked: true,
    sort_order: 1,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-6',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-paris',
    date: '2026-06-13',
    time_label: '01:00 PM',
    title: 'Lunch — Le Comptoir du Panthéon',
    subtitle: 'Classic French bistro · Latin Quarter · ~$28pp',
    type: 'food',
    emoji: '🍷',
    cost: 28,
    booked: false,
    sort_order: 2,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-7',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-paris',
    date: '2026-06-13',
    time_label: '04:00 PM',
    title: 'Seine River Cruise',
    subtitle: 'Bateaux Mouches · 1hr scenic cruise · ~$18pp',
    type: 'activity',
    emoji: '🚢',
    cost: 18,
    booked: false,
    sort_order: 3,
    created_at: '2026-01-01T00:00:00Z',
  },
  // Barcelona Day 7
  {
    id: 'it-8',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-barcelona',
    date: '2026-06-18',
    time_label: '10:00 AM',
    title: 'Train Paris → Barcelona',
    subtitle: 'TGV high-speed · 6h 30m · Gare de Lyon → Sants',
    type: 'transport',
    emoji: '🚄',
    cost: 89,
    booked: true,
    sort_order: 1,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-9',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-barcelona',
    date: '2026-06-18',
    time_label: '05:00 PM',
    title: 'Check in — Hotel Arts Barcelona',
    subtitle: 'Carrer de la Marina, 19-21 · 5★ · $310/night',
    type: 'hotel',
    emoji: '🏨',
    cost: 310,
    booked: true,
    sort_order: 2,
    created_at: '2026-01-01T00:00:00Z',
  },
  // Santorini Day 12
  {
    id: 'it-10',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-santorini',
    date: '2026-06-23',
    time_label: '08:00 AM',
    title: 'Flight BCN → JTR via Athens',
    subtitle: 'Aegean Airlines · 1 stop · 5h 20m',
    type: 'flight',
    emoji: '✈️',
    cost: 185,
    booked: true,
    sort_order: 1,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-11',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-santorini',
    date: '2026-06-23',
    time_label: '02:00 PM',
    title: 'Check in — Canaves Oia Suites',
    subtitle: 'Oia, Santorini · Caldera view · 5★ · $420/night',
    type: 'hotel',
    emoji: '🏨',
    cost: 420,
    booked: true,
    sort_order: 2,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-12',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-santorini',
    date: '2026-06-23',
    time_label: '07:00 PM',
    title: 'Sunset dinner — Ammoudi Fish Tavern',
    subtitle: 'Fresh seafood · Amoudi Bay · ~$45pp',
    type: 'food',
    emoji: '🐟',
    cost: 45,
    booked: false,
    sort_order: 3,
    created_at: '2026-01-01T00:00:00Z',
  },
  // Rome Day 18
  {
    id: 'it-13',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-rome',
    date: '2026-06-29',
    time_label: '09:00 AM',
    title: 'Flight JTR → FCO via Athens',
    subtitle: 'Aegean Airlines · 1 stop · 4h 15m',
    type: 'flight',
    emoji: '✈️',
    cost: 160,
    booked: true,
    sort_order: 1,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-14',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-rome',
    date: '2026-06-29',
    time_label: '02:00 PM',
    title: 'Colosseum & Roman Forum',
    subtitle: 'Skip-the-line tickets · Guided tour · ~$32pp',
    type: 'activity',
    emoji: '🏛️',
    cost: 32,
    booked: true,
    sort_order: 2,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'it-15',
    trip_id: 'europe-summer-2026',
    destination_id: 'dest-rome',
    date: '2026-06-29',
    time_label: '07:30 PM',
    title: 'Dinner — Da Enzo al 29',
    subtitle: 'Trastevere · Roman classics · ~$30pp',
    type: 'food',
    emoji: '🍝',
    cost: 30,
    booked: false,
    sort_order: 3,
    created_at: '2026-01-01T00:00:00Z',
  },
];

// Helper: count activities per destination
export function getActivityCount(destinationId: string): number {
  return mockItineraryItems.filter((item) => item.destination_id === destinationId).length;
}

// Helper: get items for a specific destination
export function getItemsForDestination(destinationId: string): ItineraryItem[] {
  return mockItineraryItems
    .filter((item) => item.destination_id === destinationId)
    .sort((a, b) => {
      if (a.date === b.date) return a.sort_order - b.sort_order;
      return (a.date || '').localeCompare(b.date || '');
    });
}
